name: socket rust test

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
   runs-on: ubuntu-20.04

   steps:
     - uses: actions/checkout@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: 1.42.0
     - name: Build
       run: cargo build --verbose
     - name: Test
       run: cargo test --verbose